apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sa.yaml
  - deployment.yaml
  - service.yaml
  - mapping.yaml
commonLabels:
  app: gql-edge
configMapGenerator:
- literals:
  - PORT=4000
  - NATS_HOST=nats://nats:4222
  name: gql-edge-config
