apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- deployment.yaml
- service.yaml
images:
- name: jasonblanchard/entry-gql-edge
  newName: jasonblanchard/entry-gql-edge
  newTag: latest
