apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
resources:
- sa.yaml
- deployment.yaml
- service.yaml
images:
- name: jasonblanchard/entry-gql-edge
  newName: jasonblanchard/entry-gql-edge
  newTag: latest
configMapGenerator:
- literals:
  - PORT=4000
  name: entry-gql-edge-config
